import type { Metadata } from "next";

import "./globals.css";
import { Toaster } from "./_components/ui/sonner";
import Footer from "./_components/footer";

export const metadata: Metadata = {
  title: "FSW Barber",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`antialiased`}>
        {children}
        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
